[package]
name = "keyauth"
version = "0.1.1"
edition = "2021"
description = "unoficial keyauth library using api version 1.2"
readme = "README.md"
repository = "https://github.com/D0A1V2I3D/keyauth-rust-unofficial"
license = "MIT"
documentation = "https://docs.rs/keyauth/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obfstr = "0.4.1"
webbrowser = "0.8.0"
serde_json = "1.0.86"
machine_uuid = "0.1.0"
hmac-sha256 = "1.1.4"
hex = "0.4.3"
base16 = "0.2.1"

[dependencies.uuid]
version = "1.2.1"
features = ["v4"]

[dependencies.serde]
version = "1.0.126"
features = ["derive"]

[dependencies.reqwest]
version = "0.11.12"
features = ["blocking"]